title: Chicago Teamsters LGBTQ+ Caucus
email: eliza@teamsterspridechi.org
description: >- # this means to ignore newlines until "baseurl:"
 We are the Chicago branch of the Teamsters LGBTQ+ Caucus.
 Solidarity - Equality - Respect
domain: teamsterspridechi.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.teamsterspridechi.org" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: teamsterspridechi
github_username: teamsterspridechi

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
