lang: en-US
title: Chicago Teamsters LGBTQ+ Caucus
email: eliza@teamsterspridechi.org
description: >- # this means to ignore newlines until "baseurl:"
 Official Website of the Chicago Teamsters LGBTQ+ Caucus.
 Solidarity - Equality - Respect
domain: teamsterspridechi.org
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.teamsterspridechi.org" # the base hostname & protocol for your site, e.g. http://example.com
logo: /assets/logo.png
twitter_username: teamsterspridechi
github_username: teamsterspridechi

# Build settings
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
plugins:
  - jekyll-feed


# Exclude from processing.
# The following items will not be processed, by default.
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
